### ISSUE TITLE
Error in the app

### ISSUE THREAD

**Issue by ries9112** [rajkstats/git_discoverer_app#12]
Very nice app! I was giving it a go, but it looks like there is an error currently:
![image](https://user-images.githubusercontent.com/32306488/99421190-5a112300-28bb-11eb-883e-97d74532cbd6.png)

Just wanted to let you know. Keep up the great work!
Ricky

**Comment by rajkstats** [comment]
Hey @ries9112, thanks for letting me know about the error. I have fixed it. There is an issue with the unofficial trending API  I was using. One person was kind enough to create a new end point and I have updated that in the app. 
https://gtrend.yapie.me/repositories?language=R&since=weekly. 

Glad that you liked the app!

**Comment by ries9112** [comment]
Great, glad you were able to fix the issue!

FYI though the two "trending tabs" are still displaying an error

**Comment by rajkstats** [comment]
I see. Just checked again, its working on my side. Can you clear the cache and try? or give a try incognito mode.

**Comment by ries9112** [comment]
Hmm strange, I am actually still seeing an error on my end:
![image](https://user-images.githubusercontent.com/32306488/100031191-3a459780-2db2-11eb-842b-44ffdd9b6c8e.png)

Maybe worth seeing what the logs have to say about it? Happy to help more if I can!

**Comment by rajkstats** [comment]
I see. You are looking at the old version of the app. Please try [gitdiscoverer.com](http://gitdiscoverer.com/). Now I have fixed both versions.
